image: Visual Studio 2017

environment:
  NUGET_API_KEY:
    secure: 1dXrY7H3Z6jE+Kz5Ow9VVrr4lk9cyIpcNgYt7Y3T+Ot96LT8Ajm38beDVSPoxZ0I

build_script:
  - ps: .\build.ps1

test: off

artifacts:
  - path: artifacts\*.nupkg
